Total Bookings =
COUNTROWS ( fact_bookings )

Completed Bookings =
CALCULATE (
    [Total Bookings],
    fact_bookings[is_cancelled] = 0
)

Cancelled Bookings =
CALCULATE (
    [Total Bookings],
    fact_bookings[is_cancelled] = 1
)

Cancellation Rate =
DIVIDE ( [Cancelled Bookings], [Total Bookings] )

Gross Booking Value =
SUM ( fact_bookings[booking_value] )

Cancelled Booking Value =
CALCULATE (
    [Gross Booking Value],
    fact_bookings[is_cancelled] = 1
)

Completion Rate =
DIVIDE ( [Completed Bookings], [Total Bookings] )

Average Booking Value =
AVERAGE ( fact_bookings[booking_value] )

Average Ride Distance =
AVERAGE ( fact_bookings[ride_distance] )

Average Wait Time =
AVERAGE ( fact_bookings[wait_time] )

Peak Hour Bookings =
CALCULATE (
    [Total Bookings],
    fact_bookings[is_peak_hour] = 1
)

Peak Hour Cancellation Rate =
CALCULATE (
    [Cancellation Rate],
    fact_bookings[is_peak_hour] = 1
)

Weekend Cancellation Rate =
CALCULATE (
    [Cancellation Rate],
    fact_bookings[is_weekend] = 1
)

Weekday Cancellation Rate =
CALCULATE (
    [Cancellation Rate],
    fact_bookings[is_weekend] = 0
)

Cancellation Value Share =
DIVIDE ( [Cancelled Booking Value], [Gross Booking Value] )

Model ROC-AUC =
MAX ( model_summary[best_test_roc_auc] )
